version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules
      - ./settings.yml:/settings.yml
    ports:
      - 3000:3000
    environment:
      PGHOST: db
      PGUSER: postgres
      SETTINGS_FILE: /settings.yml
  db:
    image: postgres:alpine

volumes:
  node_modules:
