FROM node:9-alpine

RUN apk update && apk add git

WORKDIR /opt/app
ADD package.json ./

RUN npm i

CMD ["./node_modules/.bin/nodemon", "-w", "src/server", "-x", "node_modules/.bin/babel-node", "src/server/keramiko/app.js"]

