version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules
      - ./settings.yml:/settings.yml
    ports:
      - 3000:3000
    environment:
      SETTINGS_FILE: /settings.yml
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  node_modules:
  pgdata:
